FORMAT: 1A
HOST: https://store-api.piflab.io/

# PIF Lab Store API

## Cart Colllection [/cart]

### Get Cart API [GET/cart/item?access_token="abc"]

+ Response 200 (application/json)
        {
            "items": [
                {
                    "id": 1,
                    "product_id": 1,
                    "name": "ABC",
                    "image_thumbnail_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/2/thumbnail.1466244676.png",
                    "price": 10000,
                    "quantity": 1
                }
            ],
            "amounts": {
                total: 70000
            },
            "access_token": "2"
        }

### Create Cart API [PUT/cart/item]
It creates a cart

+ Request (application/x-www-form-urlencoded)

        product_id=1&quantity=1

+ Response 201 (application/json)

        {
            "access_token": "def",
            "items": [
                {
                    "id": 11,
                    "product_id": 1,
                    "name": "XBox",
                    "image_thumbnail_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/2/thumbnail.1466244676.png",
                    "price": 70000,
                    "quantity": 1
                }
            ],
            "amounts": {
                total: 70000
            },
        }

### Update Cart API [PUT/cart/item{?access_token}]
It updates a cart

+ Request (application/x-www-form-urlencoded)

        product_id=1&quantity=1&access_token="def"

+ Response 200 (application/json)

        {
            "items": [
                {
                    "id": 11,
                    "product_id": 1,
                    "name": "XBox",
                    "image_thumbnail_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/2/thumbnail.1466244676.png",
                    "price": 70000,
                    "quantity": 2
                }
            ],
            "amounts": {
                total: 70000
            },
        }

## Products Colllection [/products]

### Get Products API [GET]
It lists at least 10 products

+ Response 200 (application/json)

        {
            "data": [
                {
                    "id": 2,
                    "name": "product",
                    "price": 12500,
                    "provider": "Microsoft",
                    "rating": 4,
                    "status": "sale",
                    "detail": "some text",
                    "image_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/2/origin.14662446.png",
                    "image_thumbnail_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/2/thumbnail.1466244676.png",
                    "image_detail_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/2/detail.1466244676.png",
                    "created_at": "2016-06-18T10:11:16.144073Z",
                    "updated_at": "2016-06-18T11:24:01.917424Z"
                },
                {
                    "id": 1,
                    "name": "product",
                    "price": 22,
                    "provider": "Microsoft",
                    "rating": 4,
                    "status": "sale",
                    "detail": "some text",
                    "image_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/1/origin.1466244681.png",
                    "image_thumbnail_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/1/thumbnail.1466244681.png",
                    "image_detail_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/1/detail.1466244681.png",
                    "created_at": "2016-06-18T10:11:21.985591Z",
                    "updated_at": "2016-06-18T11:38:21.83933Z"
                },
                {
                    "id": 0,
                    "name": "product",
                    "price": 22,
                    "provider": "Microsoft",
                    "rating": 4,
                    "status": "sale",
                    "detail": "some text",
                    "image_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/0/origin.1466244681.png",
                    "image_thumbnail_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/0/thumbnail.1466244681.png",
                    "image_detail_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/0/detail.1466244681.png",
                    "created_at": "2016-06-18T10:11:21.985591Z",
                    "updated_at": "2016-06-18T11:38:21.83933Z"
                }                
            ],
            "paging": {
                "next": null,
                "previous": "/products/offset=0&limit=10"
            }
        }

### Get Products By Pages API [GET/products?offset={offset}&limit={limit}]
It lists products by pages

+ Response 200 (application/json)

        {
            "data": [
                {
                    "id": 2,
                    "name": "product",
                    "price": 12500,
                    "provider": "Microsoft",
                    "rating": 4,
                    "status": "sale",
                    "detail": "some text",
                    "image_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/2/origin.14662446.png",
                    "image_thumbnail_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/2/thumbnail.1466244676.png",
                    "image_detail_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/2/detail.1466244676.png",
                    "created_at": "2016-06-18T10:11:16.144073Z",
                    "updated_at": "2016-06-18T11:24:01.917424Z"
                },
                {
                    "id": 3,
                    "name": "product",
                    "price": 22,
                    "provider": "Microsoft",
                    "rating": 4,
                    "status": "sale",
                    "detail": "some text",
                    "image_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/3/origin.1466244681.png",
                    "image_thumbnail_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/3/thumbnail.1466244681.png",
                    "image_detail_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/3/detail.1466244681.png",
                    "created_at": "2016-06-18T10:11:21.985591Z",
                    "updated_at": "2016-06-18T11:38:21.83933Z"
                }
            ],
            "paging": {
                "next": "/products/offset=3&limit=2",
                "previous": "/products/offset=0&limit=2"
            }
        }

### Create Product API [POST]
It creates a product

+ Request (application/json)

        {
            "name": "XBox",
            "price": 70000,
            "provider": "Microsoft",
            "rating": 3.5,
            "status": "sale",
            "detail": "some detail of product"
        }

+ Request (application/x-www-form-urlencoded)

        name=XBox&price=70000&provider=Microsoft&rating=3.5&status=sale&detail=some%20detail%20of%20product

+ Request (multipart/form-data; boundary=---BOUNDARY)

        -----BOUNDARY
        Content-Disposition: form-data; name="image"; filename="image.jpg"
        Content-Type: image/jpeg
        Content-Transfer-Encoding: base64

        /9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0a
        HBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIy
        MjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAABAAEDASIA
        AhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFAEB
        AAAAAAAAAAAAAAAAAAAAAP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AL+AD//Z
        -----BOUNDARY

+ Response 422 (application/json)

    + Body

            {
                "error": "Image is required"
            }

+ Response 201 (application/json)

    + Body

            {
                "id": 1,
                "name": "XBox",
                "price": 70000,
                "provider": "Microsoft",
                "rating": 3,
                "status": "sale",
                "detail": "rerum itaque cumque explicabo omnis."
                "image_url": "https://piflab-store.s3-ap-southeast-1.amazonaws.com/products/1/origin.png",
                "image_thumbnail_url": "https://piflab-store.s3-ap-southeast-1.amazonaws.com/products/1/thumbnail.png",
                "image_detail_url": "https://piflab-store.s3-ap-southeast-1.amazonaws.com/products/1/detail.png",
                "created_at": "2016-01-17T07:20:40+0000",
                "updated_at": "2016-01-17T07:20:40+0000",
            }

### Update Products API [PUT/products/{id}]
It updates a product

+ Request (application/json)

        {
            "rating": 5.1,
        }

+ Request (application/x-www-form-urlencoded)

        rating=5.1

+ Request (multipart/form-data; boundary=---BOUNDARY)

        ------WebKitFormBoundaryXBSDgs8T1omqCUw9
        Content-Disposition: form-data; name="rating"

        5.1
        ------WebKitFormBoundaryXBSDgs8T1omqCUw9--

+ Response 422 (application/json)

    + Body

            {
                "error": "Rating must be less than or equal to 5"
            }

+ Response 200 (application/json)

    + Body

            {
                "id": 1,
                "name": "XBox",
                "price": 70000,
                "provider": "Microsoft",
                "rating": 3.5,
                "status": "sale",
                "detail": "rerum itaque cumque explicabo omnis."
                "image_url": "https://piflab-store.s3-ap-southeast-1.amazonaws.com/products/1/origin.png",
                "image_thumbnail_url": "https://piflab-store.s3-ap-southeast-1.amazonaws.com/products/1/thumbnail.png",
                "image_detail_url": "https://piflab-store.s3-ap-southeast-1.amazonaws.com/products/1/detail.png",
                "created_at": "2016-01-17T07:20:40+0000",
                "updated_at": "2016-01-17T07:20:40+0000",
            }
            
### Delete Products API [DELETE/products/{id}]
It deletes a product

+ Response 200 (application/json)

    + Body

            {
                "id": 1,
                "name": "XBox",
                "price": 70000,
                "provider": "Microsoft",
                "rating": 3.5,
                "status": "sale",
                "detail": "rerum itaque cumque explicabo omnis."
                "image_url": "https://piflab-store.s3-ap-southeast-1.amazonaws.com/products/1/origin.png",
                "image_thumbnail_url": "https://piflab-store.s3-ap-southeast-1.amazonaws.com/products/1/thumbnail.png",
                "image_detail_url": "https://piflab-store.s3-ap-southeast-1.amazonaws.com/products/1/detail.png",
                "created_at": "2016-01-17T07:20:40+0000",
                "updated_at": "2016-01-17T07:20:40+0000",
            }
            
