FORMAT: 1A
HOST: https://store-api.piflab.io/

# PIF Lab Store API

## Products Colllection [/products]

### Products API [GET]
It lists all products

+ Response 200 (application/json)

        [
          {
            "name": "XBox",
            "price": 70000,
            "provider": "Microsoft",
            "rating": 3,
            "status": "sale",
            "image_url": "img/catalog/1.png",
            "detail_url": "/product/1"
          },
          {
            "name": "PS3",
            "price": 50000,
            "provider": "Sony",
            "rating": 4,
            "status": "sale",
            "image_url": "img/catalog/2.png",
            "detail_url": "/product/2"
          }
        ]
